-- Create a table to store your documents
create table documents (
  id bigserial primary key,
  content text, -- corresponds to the "text chunk"
  embedding vector(1536) -- 1536 works for OpenAI embeddings
);

Semantic Query:

-- Create a function to search for documents
create or replace function match_documents (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  similarity float
)
language sql stable
as $$
  select
    documents.id,
    documents.content,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where 1 - (documents.embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count; 
$$;

------
Supabase provides special method called Remote Procedure Call (RPC) that lets you call functions in your Postgres database like match_documents from anywhere in your code.

`supabase.rpc('match_documents')`

If similarity score is greater than matched threshold you gets the results.

e.g
```
import { openai, supabase } from './config.js';

// User query about podcasts
const query = "Jammin' in the Big Easy";
main(query);

/*
  Create an embedding from the user input and return a 
  semantically matching text chunk from the database 
*/
async function main(input) {
  // Create a vector embedding representing the input text
  const embeddingResponse = await openai.embeddings.create({
    model: "text-embedding-ada-002",
    input,
  }); 
  
  // The vector generated by OpenAI
  const embedding = embeddingResponse.data[0].embedding;
  
  // Query Supabase for nearest vector match
  const { data } = await supabase.rpc('match_documents', {
    query_embedding: embedding,
    match_threshold: 0.50, //50% of content is match
    match_count: 1 //if specified 1 only one search results
  }); 
  console.log(data);
}
```

output: Similarity is about 85%
[{id: 2, content: 'Jazz under stars (55 min): Experience a captivating night in New Orleans, where jazz melodies echo under the moonlit sky.', similarity: 0.846583600073963}]


